### ISSUE TITLE
stochQN has no _wrapper file

### ISSUE THREAD

**Issue by KaiyouHu** [david-cortes/stochQN#1]
In stochQN dir, the _init_.py has such code as 'from stochqn._wrapper import oLBFGS_free, SQN_free, adaQN_free'. But stochqn doesn't have '_wrapper'. Are the C-interfaces written in pywrapper.pyx？ If true, how can I import it. Thanks!

**Comment by david-cortes** [comment]
The `_wrapper` file gets generated once you compile `pywrapper.pyx`. Now, this is a bad practice, but I used absolute names instead of relative paths (like `from .`), so if you changed the folder/file/package names, it won't find that file.

Otherwise, you just need to compile it (e.g. `python setup.py build_ext --inplace --force` or `python setup.py install`).

**Comment by KaiyouHu** [comment]
> The `_wrapper` file gets generated once you compile `pywrapper.pyx`. Now, this is a bad practice, but I used absolute names instead of relative paths (like `from .`), so if you changed the folder/file/package names, it won't find that file.
> 
> Otherwise, you just need to compile it (e.g. `python setup.py build_ext --inplace --force` or `python setup.py install`).

I did complie it. But both windows and ubuntu16 don't success, trying conda also failed. Compile in windows，it only generated 'pywrapper.c', and in ubuntu, it generated  an extra '_wrapper.cpython-37m-x86_64-linux-gnu.so' in build dic. I still don't know how to compile correctly. Could you give your envirement conditions? Or some other suggestions?  Many thanks.

**Comment by david-cortes** [comment]
That file `_wrapper.cpython-37m-x86_64-linux-gnu.so` is the one being imported (if you see that file, it means it compiled correctly - in windows you should see a similar file ending in `.pyd`). The file will be generated inside the folder `/stochqn`, so if you run a Python instance in the folder above (where `setup.py` is located), it will import it correctly. If you want to run the Python instance from some other folder, you need to install the package (`python setup.py install`).

Please post the full error message that you get when compiling in Windows. Also are which compiler are you using in Windows? (e.g. Microsoft Visual Studio, MinGW, etc.)

EDIT: now I see you said the `_wrapper` file was in the build dir. Does it not generate any other similar file either under `/stochqn` or in the package root folder (which has `setup.py`)?

**Comment by david-cortes** [comment]
Just tested it again just in case with Python installed from the latest conda version in windows 10 and linux - it compiled fine on both (in windows using MSVC and MINGW32 as compilers and MKL as BLAS backend, in linux using GCC and with MKL and OpenBLAS as BLAS backend).

Only problem I encountered is that if the other package `findblas` which is a dependency of this tells you that you're missing `mkl-devel` and should install it with either `conda` or `pip`, the `conda` install will not make it work, while the `pip` install will - that's something I need to fix in that other package.

**Comment by KaiyouHu** [comment]
> Just tested it again just in case with Python installed from the latest conda version in windows 10 and linux - it compiled fine on both (in windows using MSVC and MINGW32 as compilers and MKL as BLAS backend, in linux using GCC and with MKL and OpenBLAS as BLAS backend).
> 
> Only problem I encountered is that if the other package `findblas` which is a dependency of this tells you that you're missing `mkl-devel` and should install it with either `conda` or `pip`, the `conda` install will not make it work, while the `pip` install will - that's something I need to fix in that other package.

I'm nearly mad. Such are my trying.
conda create -n stoch python=3.6     #### get a vs2015_runtime in conda
activate stoch
conda install cython, numpy,scipy, sklearn
pip install findblas, mkl-devel
git clone https://www.github.com/david-cortes/stochQN.git
cd stochQN
python setup.py install
But only get such result. The reason is the blas or no files found matching 'src\rtd_mock.h' or others?
` (stoch) E:\Workspace\PyCharm-workspace\BMM\stochQN>python setup.py install
running install
running bdist_egg
running egg_info
writing stochqn.egg-info\PKG-INFO
writing dependency_links to stochqn.egg-info\dependency_links.txt
writing requirements to stochqn.egg-info\requires.txt
writing top-level names to stochqn.egg-info\top_level.txt
reading manifest file 'stochqn.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'src\rtd_mock.h'
writing manifest file 'stochqn.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
Installation: Using BLAS library found in:
E:/IDE/Anaconda3/envs/stoch/Library/lib\mkl_rt.lib


skipping 'stochqn\pywrapper.c' Cython extension (up-to-date)
building 'stochqn._wrapper' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -D_FOR_PYTON -DHAS_MKL -IE:\IDE\Anaconda3\envs\stoch\lib\site-packages\numpy\core\include -Iinclude -IE:/IDE/Anaconda3/envs/stoch/Library/include -IE:\IDE\Anaconda3\envs\stoch\lib\site-packages\findblas\ -IE:\IDE\Anaconda3\envs\stoch\include -IE:\IDE\Anaconda3\envs\stoch\include /Tcstochqn\pywrapper.c /Fobuild\temp.win-amd64-3.6\Release\stochqn\pywrapper.obj /O2 /openmp
error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -D_FOR_PYTON -DHAS_MKL -IE:\IDE\Anaconda3\envs\stoch\lib\site-packages\numpy\core\include -Iinclude -IE:/IDE/Anaconda3/envs/stoch/Library/include -IE:\IDE\Anaconda3\envs\stoch\lib\site-packages\findblas\ -IE:\IDE\Anaconda3\envs\stoch\include -IE:\IDE\Anaconda3\envs\stoch\include /Tcstochqn\pywrapper.c /Fobuild\temp.win-amd64-3.6\Release\stochqn\pywrapper.obj /O2 /openmp" failed with exit status 127 `


 If you could give some suggestion, I'll appricate. And I hope you could share your installing proccess in conda so I can imitate.

**Comment by david-cortes** [comment]
Hmmm, that’s a weird error – basically it’s complaining about some incompatibility between `numpy` and the `msvc` compiler you installed, and some google search for that error suggests reinstalling. The file `src\rtd_mock.h` is not actually a problem as that file will only ever get used if you set an environment variable called `RTD` (which, in a clean windows/linux/mac installation, you won’t have, but it’s present in computers from `readthedocs.org` when they build the package).

Could you get the full error messages from the following?
* `pip install stochqn`
* `python setup.py build_ext --inplace --force --compiler=mingw32` (maybe try with `-compiler=mingw32` if it doesn’t accept it)
* Same `python setup.py build_ext --inplace --force`, but in linux.

Are you using the same MSVC compiler 2015 as the VC runtime that you installed, or do you have different versions of both?

**Comment by KaiyouHu** [comment]
> Hmmm, that’s a weird error – basically it’s complaining about some incompatibility between `numpy` and the `msvc` compiler you installed, and some google search for that error suggests reinstalling. The file `src\rtd_mock.h` is not actually a problem as that file will only ever get used if you set an environment variable called `RTD` (which, in a clean windows/linux/mac installation, you won’t have, but it’s present in computers from `readthedocs.org` when they build the package).
> 
> Could you get the full error messages from the following?
> 
> * `pip install stochqn`
> * `python setup.py build_ext --inplace --force --compiler=mingw32` (maybe try with `-compiler=mingw32` if it doesn’t accept it)
> * Same `python setup.py build_ext --inplace --force`, but in linux.
> 
> Are you using the same MSVC compiler 2015 as the VC runtime that you installed, or do you have different versions of both?

Thanks for your suggestions! I finally fix it after I uninstalled VS2017and installed VS2019, especially the VC140 tools which is not default component. I would have thought with a vc140_runtime in conda env, it could work directly., but it doesn't. And now I will read the code carefully. 
Hmm, in the Usage part of README.md, you might write sample_weights=None. But in source code, you write sample_weight=None. You use keyword arguments, and it will lead into an error.
Finally, thank you again!

**Comment by david-cortes** [comment]
> > Hmmm, that’s a weird error – basically it’s complaining about some incompatibility between `numpy` and the `msvc` compiler you installed, and some google search for that error suggests reinstalling. The file `src\rtd_mock.h` is not actually a problem as that file will only ever get used if you set an environment variable called `RTD` (which, in a clean windows/linux/mac installation, you won’t have, but it’s present in computers from `readthedocs.org` when they build the package).
> > Could you get the full error messages from the following?
> > 
> > * `pip install stochqn`
> > * `python setup.py build_ext --inplace --force --compiler=mingw32` (maybe try with `-compiler=mingw32` if it doesn’t accept it)
> > * Same `python setup.py build_ext --inplace --force`, but in linux.
> > 
> > Are you using the same MSVC compiler 2015 as the VC runtime that you installed, or do you have different versions of both?
> 
> Thanks for your suggestions! I finally fix it after I uninstalled VS2017and installed VS2019, especially the VC140 tools which is not default component. I would have thought with a vc140_runtime in conda env, it could work directly., but it doesn't. And now I will read the code carefully.
> Hmm, in the Usage part of README.md, you might write sample_weights=None. But in source code, you write sample_weight=None. You use keyword arguments, and it will lead into an error.
> Finally, thank you again!

Yes, I need to correct that, thanks for noticing!
